global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'nodejs-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['nodejs-app:9100'] 
